import path from "path";
import fs from "fs";
import { Router } from "express";
import multer from "multer";
import { pool } from "../db";
import jwt from "jsonwebtoken";

/**
 * Main API router for the backend.
 *
 * This router handles:
 * - health checks
 * - user creation and lookup
 * - login and JWT-based authentication
 * - model upload, listing, download, deletion
 * - file-based storage for saved models
 *
 * Note:
 * This file currently uses `any` in many places to avoid TypeScript
 * middleware signature issues. A future improvement would be to replace
 * those usages with proper Express Request/Response/NextFunction types.
 */
export const api: any = Router();

/**
 * Secret used to sign and verify JWT tokens.
 *
 * In production this should always come from environment variables.
 */
const JWT_SECRET = process.env.JWT_SECRET ?? "svp3rs3(r3t";

// ---------- File storage ----------

/**
 * Root directory where uploaded files are stored on disk.
 */
const STORAGE_DIR = path.resolve(process.cwd(), "storage");

/**
 * Ensure the storage directory exists before handling uploads.
 */
fs.mkdirSync(STORAGE_DIR, { recursive: true });

/**
 * Multer instance that saves uploaded files directly to disk
 * using random filenames generated by multer.
 */
const upload: any = multer({ dest: STORAGE_DIR });

/**
 * Multer instance that keeps uploaded files in memory as Buffers.
 *
 * This is used when the application wants to manually control
 * the final output path and filename.
 */
const memoryUpload: any = multer({ storage: multer.memoryStorage() });

// ---------- Auth middleware ----------

/**
 * Middleware that verifies a Bearer token and attaches the authenticated
 * user's ID to `req.user`.
 *
 * Expected header format:
 * Authorization: Bearer <token>
 *
 * On success:
 * - req.user = { user_id: number }
 *
 * On failure:
 * - returns 401 with an error message
 */
const requireAuth: any = (req: any, res: any, next: any) => {
  const authHeader: string = req.headers?.authorization ?? "";
  const token = authHeader.startsWith("Bearer ")
    ? authHeader.slice("Bearer ".length)
    : null;

  if (!token) return res.status(401).json({ error: "missing token" });

  try {
    const decoded = jwt.verify(token, JWT_SECRET) as any;
    const user_id = Number(decoded?.user_id);

    if (!Number.isFinite(user_id) || user_id <= 0) {
      return res.status(401).json({ error: "invalid token payload" });
    }

    req.user = { user_id };
    return next();
  } catch {
    return res.status(401).json({ error: "invalid token" });
  }
};

// ---------- Health ----------

/**
 * GET /health
 *
 * Checks whether the server can successfully communicate with the database.
 *
 * Response:
 * - ok: true/false
 * - dbTime: database timestamp if available
 * - error: included if the database is unavailable
 */
api.get("/health", async (_req: any, res: any) => {
  try {
    const result = await pool.query("select now() as now");
    res.json({ ok: true, dbTime: result.rows[0].now });
  } catch (err) {
    console.error("DB health check failed", err);
    res.json({ ok: false, dbTime: null, error: "db unavailable" });
  }
});

// ---------- Users ----------

/**
 * GET /users
 *
 * Returns all users in ascending user_id order.
 */
api.get("/users", async (_req: any, res: any) => {
  try {
    const result = await pool.query(
      "SELECT user_id, email, name, created_at FROM public.users ORDER BY user_id ASC",
    );
    res.json(result.rows);
  } catch (err) {
    console.error("Failed to read users", err);
    res.status(500).json({ error: "db error" });
  }
});

/**
 * POST /users
 *
 * Creates a new user.
 *
 * Expected body:
 * - email: string
 * - name: string
 *
 * Validation:
 * - both email and name are required
 */
api.post("/users", async (req: any, res: any) => {
  const email = String(req.body?.email ?? "")
    .trim()
    .toLowerCase();
  const name = String(req.body?.name ?? "").trim();

  if (!email || !name) {
    return res.status(400).json({ error: "email and name required" });
  }

  try {
    const result = await pool.query(
      `INSERT INTO public.users (email, name)
       VALUES ($1, $2)
       RETURNING user_id, email, name, created_at`,
      [email, name],
    );
    res.status(201).json(result.rows[0]);
  } catch (err) {
    console.error("Insert failed:", err);
    res.status(500).json({ error: "Database error" });
  }
});

/**
 * GET /users/exists
 *
 * Checks whether a user exists by email.
 *
 * Query params:
 * - email: string
 *
 * Response:
 * - { exists: false }
 * - { exists: true, user: ... }
 *
 * This route is intended as a frontend helper and does not authenticate users.
 */
api.get("/users/exists", async (req: any, res: any) => {
  const email = String(req.query?.email ?? "")
    .trim()
    .toLowerCase();
  if (!email) return res.status(400).json({ error: "email required" });

  try {
    const result = await pool.query(
      `SELECT user_id, email, name, created_at
       FROM public.users
       WHERE lower(email) = $1
       LIMIT 1`,
      [email],
    );

    if (result.rowCount === 0) return res.json({ exists: false });
    return res.json({ exists: true, user: result.rows[0] });
  } catch (err) {
    console.error("Exists check failed:", err);
    res.status(500).json({ error: "db error" });
  }
});

// ---------- Login ----------

/**
 * POST /login/email
 *
 * Logs in a user using an email lookup.
 *
 * Expected body:
 * - email: string
 *
 * If a matching user is found:
 * - a JWT token is returned
 * - user information is returned
 *
 * Token payload:
 * - user_id
 *
 * Token lifetime:
 * - 2 hours
 */
api.post("/login/email", async (req: any, res: any) => {
  const email = String(req.body?.email ?? "")
    .trim()
    .toLowerCase();
  if (!email) return res.status(400).json({ error: "email required" });

  try {
    const result = await pool.query(
      `SELECT user_id, email, name, created_at
       FROM public.users
       WHERE lower(email) = $1
       LIMIT 1`,
      [email],
    );

    if (result.rowCount === 0) {
      return res.status(401).json({ error: "no such user" });
    }

    const user = result.rows[0];

    const token = jwt.sign({ user_id: user.user_id }, JWT_SECRET, {
      expiresIn: "2h",
    });

    return res.json({ token, user });
  } catch (err) {
    console.error("Login failed:", err);
    res.status(500).json({ error: "db error" });
  }
});

/**
 * POST /login
 *
 * Development-only admin login.
 *
 * Expected body:
 * - username
 * - password
 *
 * Credentials are checked against environment variables:
 * - LOGIN_USER
 * - LOGIN_PASS
 *
 * This route is separate from email-based user login and returns a simple
 * dev token string.
 */
api.post("/login", async (req: any, res: any) => {
  const { username, password } = req.body ?? {};
  const envUser = process.env.LOGIN_USER ?? "admin";
  const envPass = process.env.LOGIN_PASS ?? "password";

  if (!username || !password)
    return res.status(400).send("username and password required");
  if (username !== envUser || password !== envPass)
    return res.status(401).send("invalid credentials");

  const token = `devtoken-${Date.now()}`;
  res.json({ token });
});

// ---------- Models (authenticated routes) ----------

/**
 * GET /models
 *
 * Returns all models belonging to the currently authenticated user,
 * ordered by upload time descending.
 */
api.get("/models", requireAuth, async (req: any, res: any) => {
  const userId = Number(req.user?.user_id);

  try {
    const result = await pool.query(
      `SELECT model_id, user_id, model_name, file_format, uploaded_at
       FROM public.models
       WHERE user_id = $1
       ORDER BY uploaded_at DESC`,
      [userId],
    );
    res.json(result.rows);
  } catch (err) {
    console.error("Failed to list models", err);
    res.status(500).json({ error: "db error" });
  }
});

/**
 * POST /models
 *
 * Uploads a model file for the authenticated user and creates or updates
 * a database record.
 *
 * Multipart form-data fields:
 * - file: uploaded file
 * - model_name: optional custom model name
 * - uploadedAt: optional upload timestamp
 * - project_id: optional project identifier used in folder structure
 * - model_id: optional existing model ID; if present, the model is updated
 *
 * Allowed file extensions:
 * - stl
 * - obj
 * - gltf
 * - glb
 *
 * Storage layout:
 * storage/<userId>/<projectId>/<modelName>.<ext>
 */
api.post(
  "/models",
  requireAuth,
  memoryUpload.single("file"),
  async (req: any, res: any) => {
    const userId = Number(req.user?.user_id);
    const file = req.file as any | undefined;

    if (!file) {
      return res.status(400).json({ error: "file required" });
    }

    const allowedFormats = new Set(["stl", "obj", "gltf", "glb"]);
    const original = file.originalname || "model.glb";
    const ext = path.extname(original).replace(".", "").toLowerCase();

    if (!allowedFormats.has(ext)) {
      return res.status(400).json({
        error: `invalid file_format "${ext}". Allowed: stl, obj, gltf, glb`,
      });
    }

    const defaultName = path.basename(original, path.extname(original));
    const modelName =
      String(req.body?.model_name ?? defaultName).trim() || defaultName;

    const uploadedAt = req.body?.uploadedAt
      ? new Date(req.body.uploadedAt)
      : new Date();

    const projectId =
      String(req.body?.project_id ?? "default-project").trim() ||
      "default-project";

    /**
     * Sanitize all path components before writing to disk.
     * This reduces risk from unsafe characters in user-provided values.
     */
    const safeUserId = String(userId).replace(/[^a-zA-Z0-9._-]/g, "_");
    const safeProjectId = projectId.replace(/[^a-zA-Z0-9._-]/g, "_");
    const safeModelName = modelName.replace(/[^a-zA-Z0-9._-]/g, "_");
    const safeFileName = `${safeModelName}.${ext}`;

    const saveDir = path.join(STORAGE_DIR, safeUserId, safeProjectId);
    fs.mkdirSync(saveDir, { recursive: true });

    const absPath = path.join(saveDir, safeFileName);
    fs.writeFileSync(absPath, file.buffer);

    const relativePath = path.join(safeUserId, safeProjectId, safeFileName);
    const fileSizeBytes = Number(file.size ?? 0);

    const modelIdRaw = String(req.body?.model_id ?? "").trim();
    const modelId = modelIdRaw ? Number(modelIdRaw) : null;

    try {
      /**
       * If a model_id is provided, update the existing model record.
       * Otherwise insert a new model record.
       */
      if (modelId) {
        const result = await pool.query(
          `UPDATE public.models
           SET file_path = $1,
               file_format = $2,
               model_name = $3,
               uploaded_at = $4,
               file_size_bytes = $5
           WHERE model_id = $6 AND user_id = $7
           RETURNING model_id, user_id, file_path, file_format, model_name, uploaded_at, file_size_bytes`,
          [
            relativePath,
            ext,
            modelName,
            uploadedAt,
            fileSizeBytes,
            modelId,
            userId,
          ],
        );

        if (result.rowCount === 0) {
          return res.status(404).json({ error: "model not found" });
        }

        return res.status(200).json(result.rows[0]);
      }

      const result = await pool.query(
        `INSERT INTO public.models
         (user_id, file_path, file_format, model_name, uploaded_at, file_size_bytes)
         VALUES ($1, $2, $3, $4, $5, $6)
         RETURNING model_id, user_id, file_path, file_format, model_name, uploaded_at, file_size_bytes`,
        [userId, relativePath, ext, modelName, uploadedAt, fileSizeBytes],
      );

      return res.status(201).json(result.rows[0]);
    } catch (err) {
      console.error("Failed to save model", err);
      return res.status(500).json({ error: "db error" });
    }
  },
);

/**
 * GET /models/:modelId/file
 *
 * Downloads a model file owned by the authenticated user.
 *
 * Security checks:
 * - modelId must be numeric
 * - model must exist
 * - authenticated user must own the model
 * - resolved file path must stay within STORAGE_DIR
 */
api.get("/models/:modelId/file", requireAuth, async (req: any, res: any) => {
  const userId = Number(req.user?.user_id);
  console.log("Getting model for download");

  const modelId = Number(req.params?.modelId);
  if (!Number.isFinite(modelId))
    return res.status(400).json({ error: "bad modelId" });

  try {
    const result = await pool.query(
      `SELECT model_id, user_id, file_path, file_format, model_name
       FROM public.models
       WHERE model_id = $1`,
      [modelId],
    );

    if (result.rowCount === 0)
      return res.status(404).json({ error: "not found" });

    const row = result.rows[0];
    if (row.user_id !== userId)
      return res.status(403).json({ error: "forbidden" });

    const absPath = path.resolve(STORAGE_DIR, row.file_path);

    /**
     * Prevent path traversal by ensuring the resolved path is still
     * located inside the configured storage directory.
     */
    if (!absPath.startsWith(STORAGE_DIR)) {
      return res.status(400).json({ error: "invalid path" });
    }

    if (!fs.existsSync(absPath)) {
      return res.status(404).json({ error: "file missing on server" });
    }

    const safeName = String(row.model_name ?? "model").replace(
      /[^a-zA-Z0-9._-]/g,
      "_",
    );

    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${safeName}.${row.file_format}"`,
    );

    return res.sendFile(absPath);
  } catch (err) {
    console.error("Failed to send model file", err);
    return res.status(500).json({ error: "server error" });
  }
});

/**
 * DELETE /models/:modelId
 *
 * Deletes a model owned by the authenticated user.
 *
 * This removes:
 * - the row from the database
 * - the stored file from disk if it exists
 */
api.delete("/models/:modelId", requireAuth, async (req: any, res: any) => {
  console.log("attempting to delete model");

  const userId = Number(req.user?.user_id);
  const modelId = Number(req.params?.modelId);

  if (!Number.isFinite(modelId))
    return res.status(400).json({ error: "bad modelId" });

  try {
    const find = await pool.query(
      `SELECT model_id, user_id, file_path
       FROM public.models
       WHERE model_id = $1`,
      [modelId],
    );

    if (find.rowCount === 0)
      return res.status(404).json({ error: "not found" });

    const row = find.rows[0];
    if (row.user_id !== userId)
      return res.status(403).json({ error: "forbidden" });

    await pool.query(`DELETE FROM public.models WHERE model_id = $1`, [
      modelId,
    ]);

    const absPath = path.resolve(STORAGE_DIR, row.file_path);
    if (absPath.startsWith(STORAGE_DIR) && fs.existsSync(absPath)) {
      fs.unlinkSync(absPath);
    }

    return res.json({ ok: true });
  } catch (err) {
    console.error("Failed to delete model", err);
    return res.status(500).json({ error: "server error" });
  }
});

// ---------- Local save helpers ----------

/**
 * POST /save-model
 *
 * Saves an uploaded model file directly to the local storage directory.
 *
 * Multipart form-data fields:
 * - model: uploaded file
 * - projectId: optional project folder name
 *
 * This route writes to disk only and does not create or update
 * a database model record.
 */
api.post(
  "/save-model",
  requireAuth,
  memoryUpload.single("model"),
  (req: any, res: any) => {
    try {
      const userId = String(req.user?.user_id);
      const projectId = String(req.body.projectId || "default-project");

      if (!userId) {
        return res.status(401).json({ error: "unauthorized" });
      }

      if (!req.file) {
        return res.status(400).json({ error: "No file uploaded" });
      }

      const safeUserId = userId.replace(/[^a-zA-Z0-9._-]/g, "_");
      const safeProjectId = projectId.replace(/[^a-zA-Z0-9._-]/g, "_");
      const safeFileName = String(req.file.originalname || "model.glb").replace(
        /[^a-zA-Z0-9._-]/g,
        "_",
      );

      const saveDir = path.join(
        process.cwd(),
        "storage",
        safeUserId,
        safeProjectId,
      );
      fs.mkdirSync(saveDir, { recursive: true });

      const filePath = path.join(saveDir, safeFileName);
      fs.writeFileSync(filePath, req.file.buffer);

      return res.json({
        message: "File saved successfully",
        filePath,
      });
    } catch (error) {
      console.error(error);
      return res.status(500).json({ error: "Failed to save file" });
    }
  },
);

/**
 * GET /saved-models
 *
 * Returns a list of all files stored on disk for the authenticated user.
 *
 * The response includes:
 * - projectId
 * - fileName
 * - relativePath
 * - absolutePath
 * - sizeBytes
 * - modifiedAt
 *
 * Results are sorted by most recently modified first.
 */
api.get("/saved-models", requireAuth, async (req: any, res: any) => {
  try {
    const userId = String(req.user?.user_id);
    const safeUserId = userId.replace(/[^a-zA-Z0-9._-]/g, "_");

    const userDir = path.join(STORAGE_DIR, safeUserId);

    if (!fs.existsSync(userDir)) {
      return res.json([]);
    }

    const results: Array<{
      projectId: string;
      fileName: string;
      relativePath: string;
      absolutePath: string;
      sizeBytes: number;
      modifiedAt: string;
    }> = [];

    const projectDirs = fs.readdirSync(userDir, { withFileTypes: true });

    for (const entry of projectDirs) {
      if (!entry.isDirectory()) continue;

      const projectId = entry.name;
      const projectDir = path.join(userDir, projectId);

      const files = fs.readdirSync(projectDir, { withFileTypes: true });

      for (const file of files) {
        if (!file.isFile()) continue;

        const absPath = path.join(projectDir, file.name);
        const stats = fs.statSync(absPath);

        results.push({
          projectId,
          fileName: file.name,
          relativePath: path.join(safeUserId, projectId, file.name),
          absolutePath: absPath,
          sizeBytes: stats.size,
          modifiedAt: stats.mtime.toISOString(),
        });
      }
    }

    results.sort(
      (a, b) =>
        new Date(b.modifiedAt).getTime() - new Date(a.modifiedAt).getTime(),
    );

    return res.json(results);
  } catch (err) {
    console.error("Failed to list saved models", err);
    return res.status(500).json({ error: "Failed to list saved models" });
  }
});
